### PR TITLE
feat: Add implementation of INY and DEY opcode

### PR DESCRIPTION
**Pull request by Prabhat1308**
fixes the issue #20 and #25
checks out the INY and DEY opcode from #6 master instruction tracker

### CODE REVIEW

**Comment by goblinoats** [comment]
On the face it, this looks good to me. Assuming the tests pass?

**Comment by Prabhat1308** [comment]
I did run nargo test on both inx and iny but the helpers directory code throws errors which #22 is supposed to fix. 
I also ran 
```
cargo run --release test_roms/cpu/nestest.nes --trace --instr_name iny
```
and I am successfully getting a trace.

**Comment by Prabhat1308** [comment]
Hi . @goblinoats  I have checked and tested the code and and both opcodes are working once #22 gets merged.
There was an error in the tests in inx example where its was passing even when zero flag was not set when X = 0
```
fn test_0() -> Field {
    main(
        1,
        [343432, 343433, 343434, 343435, 343436, 343437, 343438, 343439, 343440],
        [8203, 79, 8203, 8203, 80, 8202, 8202, 8205, 8205],
         [49231, 200, 49232, 49232, 224, 0, 1, 36, 36], //incorrect test , since zero flag is not set before .
        [49231, 200, 49232, 49232, 224, 0, 1, 38, 36],  //corrected test
        [0, 0, 1, 0, 0, 0, 1, 0, 1]
    )
}
```
This has been corrected by @matthieuauger in his PR #24 .

**Comment by matthieuauger** [comment]
Oops @Prabhat1308 just noticed we developed the same DEY opcode, I pushed it this morning following implementation of DEX yesterday evening. My bad I should have created the related issue

**Comment by goblinoats** [comment]
There's a small conflict for your PRs @Prabhat1308 following #22 but once you resolve that and double check it's all good I will merge them in.

**Comment by Prabhat1308** [comment]
@goblinoats I have resolved the merge conflicts.

**Comment by matthieuauger** [comment]
@Prabhat1308 in order to keep git history clean you should rebase on main instead of merging main in your branch. I can help on this if you need to

**Comment by Prabhat1308** [comment]
@matthieuauger sure , would like some help

**Comment by goblinoats** [comment]
👍

**Pull request merged**
