### PR TITLE
Feat/add inc dec

### LINKED ISSUE #27: Implement INC AND DEC opcodes
INC opcode 
increments the contents of the memory location .
appropriates the zero flag and negative flag after the operation.

DEC opcode
decrements the contents of the memory location.
appropriates the zero flag and negative flag after the operation.

### PR DESCRIPTION
**Pull request by Prabhat1308**
fixes #27 . 
changes the addressing calculations to u32 to avoid overflow errors.

### CODE REVIEW

**Comment by Prabhat1308** [comment]
@goblinoats . Since this is my first PR involving code with multiple addressing , I would like that you check this for technical soundness of the concept for test vectors if they are correctly made.

**Comment by goblinoats** [comment]
We should move the addressing out to shared logic, as it was before so it only needs to be written once. Each instruction can use an addressing helper.

One of the challenges here is that each instruction is going to have a variable number of read/writes depending on the addressing mode.

I think one way forward is to simply pad the instruction with a null op, so each instr has a fixed number of read/writes. This does add some overhead. We could instead think about splitting out each instruction into separate address modes. As the plan is to run each instruction in its own process and recursively aggregate the results, this separation suits a parallel execution model.

**Comment by Prabhat1308** [comment]
@goblinoats I have added the addressing helper logic where it takes a constant read/write . The implementation with hashmap was not possible in noir because I had to instantiate and fill the hashmap in a separate function . declaration and instantiation like 
```
let hashmap = [ {x,y} , {w,z}];
```
is not yet possible in noir. 
Please review the code and let me know any improvements.
Apologies for not being able to implement the intended functionality which we discussed.

**Comment by goblinoats** [comment]
looks great 👍

**Pull request merged**
