### PR TITLE
feat : add sec-sei-sed opcodes

### PR DESCRIPTION
**Pull request by Prabhat1308**
fixes issue #30 
checks out sei , sec , sed opcodes from master tracker

### CODE REVIEW

**Comment by Prabhat1308** [comment]
I was trying to implement the set functions for the interrupt disable and decimal flag bits but for some reason they do not change even after calling the functions and remain the same . I tried to look for the error but could not find a concrete reason for this .

**Comment by goblinoats** [comment]
Is there still an issue with the intterupt disable and decimal flag?

**Comment by goblinoats** [comment]
Instead of merging branches into each other, you should get used to rebasing your code onto main. This will make your commit history nice and readable and I find it way easier to reason about what's happening anyway. Merging this into that into this gets my head spinning. 

You can do it interactively if you run the command
```
git rebase -i main
```
Squash all the noisy commits into a clean set of commits on top of main. Then those commits will be replayed over main. That's it. If there are conflicts during the replay you resolve them so the code works and then you can interactively (continue). If something seems scary and horrible, just abort and try again. Voila.

**Comment by Prabhat1308** [comment]
@goblinoats I have done the changes for more cleaner git commit history . Please have a look.
Sorry for the late changes . I was out of town and forgot my laptop charger.

**Comment by goblinoats** [comment]
lgtm! 👍

**Pull request merged**
